apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mpetit480/TEST.git
    path: argo
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
