apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
  namespace: test
spec:
  template:
    spec:
      containers:
      - name: hello-world
        image: busybox
        command:
          - "sh"
          - "-c"
          - "ls -l /usr/bin; echo ReBonjour; date"
      restartPolicy: Never
