apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
      - name: hello-world
        image: busybox
        command:
          - "sh"
          - "-c"
          - "ls -l /; echo Bonjour; date"
      restartPolicy: Never
